version: "3.9"

services:
  database:
    image: mongo:7
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: transportation_system
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mynet
  # PostgreSQL (có thể xóa nếu không cần)
  # postgres:
  #   image: postgres:16
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: odoo
  #     POSTGRES_DB: transportation_system
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - mynet
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DEVICE: cpu
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/video_test:/backend/app/video_test
    depends_on:
      - database
    networks:
      - mynet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mynet

volumes:
  mongodata:
  # pgdata:  # PostgreSQL volume (có thể xóa nếu không cần)

networks:
  mynet:


# docker compose up --build

